/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: husk3y (https://sketchfab.com/husk3ys)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/banana-cat-e770c6fa7c644aa1b47dadedd6c57ecc
Title: Banana Cat
*/
// @ts-nocheck

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  const model = useRef(null);
  const bounceHeight = 0.2; // max bounce
  const bounceSpeed = 19; // higher = faster bounce

  useFrame(({ clock }) => {
    const t = clock.elapsedTime * bounceSpeed;
    if (!props.talking) {
      model.current.rotation.y = Math.sin(clock.elapsedTime) * 0.1; // small head sway
      model.current.position.y = Math.sin(clock.elapsedTime * 2) * 0.08; // subtle breathing
    }
    if (props.talking) {
      model.current.position.y = Math.abs(Math.sin(t)) * bounceHeight;
    }
  });

  return (
    <group {...props} dispose={null} ref={model}>
      <group position={[0, 1.213, -1.141]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials.Material}
          skeleton={nodes.Object_7.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
